# Generated by Django 3.0.2 on 2020-06-17 05:43

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200617_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='Drama', max_length=66, size=6),
            preserve_default=False,
        ),
    ]
