# Generated by Django 3.0.2 on 2020-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200617_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite',
            field=models.CharField(default='Drama', max_length=200),
            preserve_default=False,
        ),
    ]
