# Generated by Django 3.0.2 on 2020-06-12 08:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('poster', models.URLField()),
                ('background', models.URLField()),
                ('vote_average', models.FloatField()),
                ('content', models.TextField()),
                ('genres', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('tmdb_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
