# Generated by Django 3.0.2 on 2020-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('poster', models.URLField()),
                ('background', models.URLField()),
                ('vote_average', models.FloatField()),
                ('content', models.TextField()),
                ('tmdb_id', models.IntegerField()),
            ],
        ),
    ]
