# Generated by Django 3.0.2 on 2020-06-14 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20200614_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('1', '부적절한 홍보 게시글'), ('2', '음란성 또는 청소년에게 부적합한 내용'), ('3', '명예훼손 / 사생활 침해 및 저작권침해 등'), ('4', '기타')], max_length=1)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
