# Generated by Django 3.0.2 on 2020-06-15 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('reviews', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=475557, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('1', '부적절한 홍보 게시글'), ('2', '음란성 또는 청소년에게 부적합한 내용'), ('3', '명예훼손 / 사생활 침해 및 저작권침해 등'), ('4', '기타')], max_length=200),
        ),
    ]
